#dubbo配置
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    #正式环境
    #url: jdbc:mysql://rm-2ze9b79wd9nddvce8.mysql.rds.aliyuncs.com:3306/bubuduo-duole
    #本地环境
    url: jdbc:mysql://1.116.133.114:3306/ry?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    #测试环境
    #url: jdbc:mysql://rdsb67neyrayvf2.mysql.rds.aliyuncs.com:3306/weather?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    #username: coohua
    #password: 86_Coohua_Com_1301
    #读写分离库
    #url: jdbc:mysql://rm-m5ew0fp38tm118428no.mysql.rds.aliyuncs.com:3306/ry1?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    #测试环境
#    url: jdbc:mysql://rm-m5ew0fp38tm118428no.mysql.rds.aliyuncs.com:3306/ry?allowMultiQueries=true&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    #username: coohua
    #password: KoZg32nu6q
    #url: jdbc:mysql://127.0.0.1:3306/ry?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    #url: jdbc:mysql://192.168.2.137:3306/ry?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
#    url: jdbc:mysql://127.0.0.1:3306/ry1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: 123456
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 1
    maxActive: 10
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 3600000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 3600000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
druid:
  config:
    user-name: root
    password: root
    url-mapping: /druid/*
  redis:
    #host: 120.27.18.22
    host: 127.0.0.1
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 10000ms
    lettuce:
      pool:
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 10
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 100
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms